### ISSUE TITLE
Railcraft cart TNT console spam

### ISSUE THREAD

**Issue by HaoSs07** [MyEssentials/MyTown#11]
&gt;16:23:05 [SEVERE]  [37;22m[ [32;1mMyTown [37;22m]Error in entity EntityCartTNT['entity.Railcraft.railcraft.cart.tnt.name'/770, l='TheCore', x=1068.89, y=12.35, z=-136.78] pre-update check [0m

java.lang.ClassCastException: mods.railcraft.common.carts.EntityCartTNT cannot be cast to railcraft.common.api.carts.IExplosiveCart

  at ee.lutsu.alpha.mc.mytown.event.prot.RailCraft.update(RailCraft.java:42)

  at ee.lutsu.alpha.mc.mytown.event.ProtectionEvents.tickStart(ProtectionEvents.java:199)

  at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:28)

  at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:122)

  at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:295)

  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:816)

  at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)

  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:728)

  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:612)

  at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

**Comment by jgoett154** [comment]
Looks like Railcraft got re-factored and something was changed. What minecraft version, an mytown version are you running currently? Also, sorry I haven't been around.

**Comment by HaoSs07** [comment]
right now. none. i stopped the server. but i had latest version by Torins

**Comment by jgoett154** [comment]
Oh ok. Ill still look into it :p

**Comment by jgoett154** [comment]
Fixed
