### ISSUE TITLE
Crashing on launch - MinecraftEdu 1.6.4 server

### ISSUE THREAD

**Issue by bwestplaysdrums** [MyEssentials/MyTown#27]
Hi there,

I'm using MinecraftEdu 1.6.4, built on MCP 8.11, FML v6.5.20.1 337, Forge 9.11.1.0.
Mods are: BiblioCraft 1.5.1, BiomesOPlenty 1.1.2, Colorful_Armor 1.7, Dynmap 1.9-75, MyTown 1.6.1.12, pamharvestcraft 1.1.4, MrCrayfish's Furniture Mod 3.2, forgeperms-1.6.1.5.jar.

MinecraftEdu 1.6.4 server launches successfully without MyTown/MyTown Lib/Forge Perms.  Getting the following crash report when trying to launch with them:

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 11/14/13 11:18 PM
Description: Exception in server tick loop

java.lang.RuntimeException: no SQLite library found
    at ee.lutsu.alpha.mc.mytown.MyTown.modsLoaded(MyTown.java:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:545)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:194)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:174)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:105)
    at cpw.mods.fml.common.Loader.serverStarted(Loader.java:758)
    at cpw.mods.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:319)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
Caused by: java.sql.SQLException: no SQLite library found
    at org.sqlite.Conn.open(Conn.java:136)
    at org.sqlite.Conn.<init>(Conn.java:57)
    at org.sqlite.JDBC.createConnection(JDBC.java:77)
    at org.sqlite.JDBC.connect(JDBC.java:64)
    at ee.lutsu.alpha.mc.mytown.sql.Database.connect(Database.java:184)
    at ee.lutsu.alpha.mc.mytown.MyTownDatasource.init(MyTownDatasource.java:39)
    at ee.lutsu.alpha.mc.mytown.MyTown.modsLoaded(MyTown.java:122)
    ... 29 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Mac OS X (x86_64) version 10.8.4
    Java Version: 1.7.0_11, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 258784120 bytes (246 MB) / 378208256 bytes (360 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 1 total; -Xmx2048M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 13, tcache: 0, allocated: 1, tallocated: 59
    FML: MCP v8.11 FML v6.4.20.1?337 Minecraft Forge 9.11.1.0 12 mods loaded, 12 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{6.4.20.1?337} [Forge Mod Loader](minecraftedu_server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{9.11.1.0} [Minecraft Forge](minecraftedu_server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.5.1} [BiblioCraft](BiblioCraft[v1.5.1].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiomesOPlenty{1.1.2} [Biomes O' Plenty](BiomesOPlenty-universal-1.6.4-1.1.2.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Colorful_Armor{1.7} [Colorful Armor](Colorful_Armor_1.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Dynmap{1.9-75} [Dynmap](Dynmap-1.9-forge-9.10.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MyTown{1.6.1.10} [MyTown](MyTown-1.6.1.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Errored
    pamharvestcraft{1.0} [Pam's HarvestCraft Base](Pam's HarvestCraft 1.6.4 v1.1.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    cfm{3.2} [?4MrCrayfish's Furniture Mod]([Forge]FurnitureModv3.2%281.6.4%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgePerms{1.0.0} [ForgePerms](forgeperms-1.6.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PermissionsEx{1.5.0.0} [PermissionsEx](forgeperms-1.6.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 100; []
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by jgoett154** [comment]
That error generally occurs because MyTown lib is missing or incorrectly installed. Make sure the MyTown lib is in the mods folder, other than that I am not sure right now and will look into it in the morning :)

**Comment by bwestplaysdrums** [comment]
Sounds good.  I'm not sure in what way I could be installing it incorrectly, haha - the MyTown lib is definitely in the mods folder.  MinecraftEdu by default has a mods/[version, i.e. 1.6.4] folder for added organization, so I tried moving everything to just /mods but the same issue persisted.  Thanks for looking into it :-)

**Comment by jgoett154** [comment]
Haha, no problem :) I noticed its being run on Mac OS X, not sure if that would have anything to do with it.

Just tossed MyTown 1.6.1.12, ForgePerms 1.6.1.5, and MyTown lib into the mods folder of a plain Forge server (non-mcpc+) and it started without any issues. I will look into it some more however and see if it is something I am doing :)

**Comment by bwestplaysdrums** [comment]
Shouldn't be OS X - I've had MyTown working with MinecraftEdu 1.5.2 on both Windows and OS X before.

Hmm.  I'll try out a normal Forge server on 1.6.4 and see if I get the same result.  Otherwise it looks like MinecraftEdu is the culprit here, which kinda sucks.

**Comment by bwestplaysdrums** [comment]
Well, I take that back.  Just tried a normal Forge server (9.11.1.942), non-MinecraftEdu, only mods being the same versions of MyTown/MyTown lib/ForgePerms as before, and again the server crashes on startup, so it's not just a MinecraftEdu thing.  Let me boot into Windows and try my luck there.

**Comment by bwestplaysdrums** [comment]
MinecraftEdu 1.6.4 Server with MyTown 1.6.1.12/Forge Perms 1.6.1.5/MyTown lib started up successfully on Windows, but crashed on OS X with the same error as above.

As I mentioned before, I have MyTown 1.5.1 successfully working on a MinecraftEdu 1.5.2 server on both Windows and OS X, so sounds like something changed between MyTown 1.5.1 and 1.6.1.12 that's causing the problem.

**Comment by jgoett154** [comment]
Sorry I didn't respond sooner. I don't know what would have changed between the two that would have caused OS X to not work. I will work on finding out the issue however.
